CREATE TABLE StudentTable (
    StudentID INT IDENTITY(1000,1) PRIMARY KEY, 
    FullName NVARCHAR(100),
    TC NVARCHAR(11), 
    IBAN NVARCHAR(34),
    PhoneNumber NVARCHAR(15), 
    BedNumber TINYINT, 
    RoomNumber INT, 
    ExitTime DATETIME,
    EntryTime DATETIME, 
    Deposit DECIMAL(10, 2), 
    BirthDate DATE, 
    Department NVARCHAR(100), 
    Grade NVARCHAR(10),
    University NVARCHAR(100), 
    RoomID INT,
	DormBlockID INT,
	DormID INT,
    MealID INT, 
	PaymentID NVARCHAR(50),
    RegistrationDate DATE, 
	ParentID INT,
    FOREIGN KEY (RoomID) REFERENCES RoomTable(RoomID), 
    FOREIGN KEY (DormBlockID) REFERENCES DormBlockTable(DormBlockID)
    FOREIGN KEY (DormID) REFERENCES DormTable(DormID),
	FOREIGN KEY (MealID) REFERENCES MealTable(MealID),
	FOREIGN KEY (PaymentID) REFERENCES Paymenttable(PaymentID),
	FOREIGN KEY (ParentID) REFERENCES ParentTable(ParentID)
);
